// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhfgBRmHGFrLuS-GiGnnalfCxJp1Tb5O4',
    appId: '1:859772978514:android:c5ece6a64699583493e68b',
    messagingSenderId: '859772978514',
    projectId: 'memories-book-886fc',
    storageBucket: 'memories-book-886fc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiQl8MxmX7iBaH_No0OeA9l8fVZfYyvzs',
    appId: '1:859772978514:ios:310f642f267b99f693e68b',
    messagingSenderId: '859772978514',
    projectId: 'memories-book-886fc',
    storageBucket: 'memories-book-886fc.firebasestorage.app',
    iosBundleId: 'com.memories.book.entry.memoriesEntry',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWibykv0kaTWN6pipQh4wgMSgkaFUu-Ns',
    appId: '1:859772978514:web:430dfea6770e337193e68b',
    messagingSenderId: '859772978514',
    projectId: 'memories-book-886fc',
    authDomain: 'memories-book-886fc.firebaseapp.com',
    storageBucket: 'memories-book-886fc.firebasestorage.app',
    measurementId: 'G-BYKC8XZ626',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiQl8MxmX7iBaH_No0OeA9l8fVZfYyvzs',
    appId: '1:859772978514:ios:310f642f267b99f693e68b',
    messagingSenderId: '859772978514',
    projectId: 'memories-book-886fc',
    storageBucket: 'memories-book-886fc.firebasestorage.app',
    iosBundleId: 'com.memories.book.entry.memoriesEntry',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWibykv0kaTWN6pipQh4wgMSgkaFUu-Ns',
    appId: '1:859772978514:web:d5c8ae249f0ce62893e68b',
    messagingSenderId: '859772978514',
    projectId: 'memories-book-886fc',
    authDomain: 'memories-book-886fc.firebaseapp.com',
    storageBucket: 'memories-book-886fc.firebasestorage.app',
    measurementId: 'G-PB27NW575L',
  );

}